### ISSUE TITLE
Benefits?

### ISSUE THREAD

**Issue by sospedra** [developit/mitt#10]
Why to choose Mitt over native EventEmitter?
Just wondering

**Comment by developit** [comment]
Under Node, I don't think it would make sense.  This is probably better-suited to a browser environment.

**Comment by developit** [comment]
I've added a note to the readme that indicates Mitt was built with the browser in mind.

**Comment by sospedra** [comment]
Wohoo! Now we're talking seriously, awesome stuff! 👍

**Comment by tunnckoCore** [comment]
Maybe some benchmarks may answer too. :)

**Comment by tonyalaribe** [comment]
can mitt be used in place of something like redux or mobx?

**Comment by svincent** [comment]
IMO those are both different tools meant for a very different job. mitt is an event emitter, not a state manager. As such, it's meant to be used in situations where you have one piece of code that needs to react to actions on another piece of code. I'm not super familiar with redux and mobx, but my impression is they are intended primarily as the connonical location where your application stores sateful information.

**Comment by sospedra** [comment]
Agree @svincent, you could - as an abstract concept - replace the Flux **dispatcher** with Mitt. But not the whole Redux.

**Comment by tonyalaribe** [comment]
I see. But its very possible to manage state in a root component or an external class, and use mitt to comunicate between the class state, and child components? I'm trying to figure out use cases for mitt

**Comment by sospedra** [comment]
As per Redux replacer yes. But what you're talking about is `react-redux` which is the one who's exposing `Provider`.

**Comment by tunnckoCore** [comment]
@tonyalariba, mitt is just event emitter and so you can use it as like other EEs. emitters are very powerful concept and are used almost evrywhere - even, each stream is emitter. they are great for state handling.

**Comment by developit** [comment]
Good discussion and it's nice to see people making the right distinctions here.  Mitt might be a way to implement the subscription mechanism of `react-redux`, and possibly the idea of observing changes to state (via the `*` event).  However, it doesn't hold state - that you'd be implementing outside of Mitt.

If anyone is interested, a while back there was an interesting discussion about how small one could make a redux stand-in.  Redux is already quite small (3kb) and includes things that alternatives wouldn't account for like DevTools integration, middlewares, pluggable reducers, etc (I'm not a big redux user but from what I understand these things are nice to have).  If interested though, here's my tweet-sized redux implementation:

```js
redux=(r,s=r(r._,{}),l=[])=>({
  dispatch(a){s=r(s,a);l.map(b=>b(s))},
  subscribe:f=>(l.push(f),i=>l.splice(i=l.indexOf(f), !!~i)),
  getState:()=>s
})
```

... and a demo of it working: https://jsfiddle.net/developit/4qedL5c2/

**Comment by tunnckoCore** [comment]
Yea there is also `redux-lite` and video for how it was created.

All these are just paradigms, conventions, principles and patterns. Once you got them, you can do what you want and start something from scratch or reimplement some popular library.
