### ISSUE TITLE
Fix TypeScript type of Handler

### ISSUE THREAD

**Issue by feimosi** [developit/mitt#112]
Currently `Handler` is typed like this:
```ts
declare type Handler<T = any> = (event?: T) => void;
```
It makes TypeScript require event handlers to support missing event value, e.g:
```ts
const handleUpdate = (event?: UpdateEvent) => {};
```
That makes it impossible to enforce event presence.
I think `?` should be removed because the developer should be responsible for setting the right type. For empty event you can always use:
```ts
eventEmitter.on<void>(Event.Update, handleUpdate);
```

**Comment by ChiaJune** [comment]
same here

**Comment by hellothursday** [comment]
I have the same problem. 

```ts
const callback = (result: string) => {
     // ...
}
emitter.on('my-event', callback)
```

then i get

```
No overload matches this call.
  Overload 1 of 2, '(type: "*", handler: WildcardHandler): void', gave the following error.
    Argument of type '"my-event"' is not assignable to parameter of type '"*"'.
  Overload 2 of 2, '(type: string | symbol, handler: Handler<string>): void', gave the following error.
    Argument of type '(result: string) => void' is not assignable to parameter of type 'Handler<string>'.
      Types of parameters 'result' and 'event' are incompatible.
        Type 'string | undefined' is not assignable to type 'string'.
          Type 'undefined' is not assignable to type 'string'.
```

but If I add `?`,  the problem is solved.

**Comment by fanquan** [comment]
> I have the same problem.
> 
> ```ts
> const callback = (result: string) => {
>      // ...
> }
> emitter.on('my-event', callback)
> ```
> 
> then i get
> 
> ```
> No overload matches this call.
>   Overload 1 of 2, '(type: "*", handler: WildcardHandler): void', gave the following error.
>     Argument of type '"my-event"' is not assignable to parameter of type '"*"'.
>   Overload 2 of 2, '(type: string | symbol, handler: Handler<string>): void', gave the following error.
>     Argument of type '(result: string) => void' is not assignable to parameter of type 'Handler<string>'.
>       Types of parameters 'result' and 'event' are incompatible.
>         Type 'string | undefined' is not assignable to type 'string'.
>           Type 'undefined' is not assignable to type 'string'.
> ```
> 
> but If I add `?`, the problem is solved.
> 
> ```ts
> const callback = (result?: string) => {
>     if (result) {
>         // ...
>     }
> }
> emitter.on('my-event', callback)
> ```

It's the same with me， but I don't know why

**Comment by wtyang** [comment]
try this
```
import mitt, { Handler } from 'mitt';
const callback: Handler = (arg: string) =>{
       ...
 }
```

**Comment by zcabjro** [comment]
I'm not a fan of having to keep spread-out invocations of `on` and `emit` in sync, so have typed the emitter using the below pattern. Incidentally, this also disallows omitting the event argument.

```ts
import mitt, { Handler } from 'mitt';

type Emits<EventType extends string | symbol, T> = {
  on(type: EventType, handler: (arg: T) => void): void;
  off(type: EventType, handler: (arg: T) => void): void;
  emit(type: EventType, arg: T): void;
};

type Emitter = Emits<'a', { a: number }> & Emits<'b', { b: string }>;

export const emitter: Emitter = mitt();
```

**Comment by williamyeny** [comment]
Apologies for bumping an old issue, but to add on to @zcabjro's comment, this is how Mitt recommends TypeScript usage according to its [README](https://github.com/developit/mitt#typescript):

```typescript
import mitt from 'mitt';

type Events = {
  updateName: string;
  updateAge?: number;
};

const emitter = mitt<Events>();

emitter.on('updateName', (name) => {}); // 'name' has inferred type 'string'
emitter.emit('updateName', 'bob'); // Valid
emitter.emit('updateName', 42); // Error: Argument of type 'number' is not assignable to parameter of type 'string'. (2345)

emitter.on('updateAge', (age) => {}); // 'age' has inferred type 'number'
emitter.emit('updateAge', 12); // Valid
emitter.emit('updateAge'); // Valid
```

In case anyone is googling for a clearer example, hope this helps!
