### ISSUE TITLE
Cannot find namespace 'mitt'.Vetur(2503)

### ISSUE THREAD

**Issue by RamirezET** [developit/mitt#119]
just copy code from readme to vscode
`import mitt from 'mitt'
const emitter: mitt.Emitter = mitt()`
then I got **Cannot find namespace 'mitt'.Vetur(2503)**

how should i do

**Comment by Rosefalk** [comment]
Same issue with TS: Cannot find namespace 'mitt'.ts(2503)

const emitter: _mitt_.Emitter = mitt() @

**Comment by jogunism** [comment]
this works for me.
`
import mitt from "mitt";
const emitter = mitt();
export default emitter;
`

**Comment by Rosefalk** [comment]
@jogunism yeah using the library works fine. It's the type definition we have an issue with 👍🏼

**Comment by saltchang** [comment]
@RamirezET @Rosefalk 

Same issue here,
but I tried this:

```typescript
import mitt, { Emitter } from 'mitt';

const emitter: Emitter = mitt();

export default emitter;
```

it works for me.

**Comment by Rosefalk** [comment]
> 
> 
> @RamirezET @Rosefalk
> 
> Same issue here,
> but I tried this:
> 
> ```ts
> import mitt, { Emitter } from 'mitt';
> 
> const emitter: Emitter = mitt();
> 
> export default emitter;
> ```
> 
> it works for me.

I tried that before, but must've made a mistake - it seems to work and compiler has no issue with it.

Thank you.

Another thing I found working was using mitt itself as the type ( emitter = typeof mitt).

**Comment by developit** [comment]
The docs have been updated to recommend the above approach.
