### ISSUE TITLE
Embedded Loggin

### ISSUE THREAD

**Issue by bkhatkov** [developit/mitt#120]
Hello guys,

Are there any plans to have any kind of embedded logging (to console) for development mode? We are switching from Vue emitter to mitt in preparation to Vue 3 (where it is deprecated) and struggling a bit as vue devtool is not able track mitt events.

**Comment by developit** [comment]
Hmm - could you use wildcard listeners?

```js
let emitter = mitt();

// log all events to console:
emitter.on('*', (type, ...args) => {
    console.info(`event(${type}): `, ...args);
});
```
