### ISSUE TITLE
Talks between modules without exposing emitter to the window

### ISSUE THREAD

**Issue by SorinGFS** [developit/mitt#121]
I try to understand if is possible to use `emitter` to emit in one module and to receive in another without exposing `emitter` to the window. I'm a little afraid to put an emitter in the window because from what I see there is no possibility to check the sender of an event. Maybe the assumption is unjustified, I don't know, but I wouldn't rely too much on browser security.
So, how should I resolve this issue?

**Comment by developit** [comment]
The correct solution for this would be to use cross-document messaging, which provides a robust security model that allows both the message sender and recipient to validate.

**Comment by SorinGFS** [comment]
> 
> 
> The correct solution for this would be to use cross-document messaging, which provides a robust security model that allows both the message sender and recipient to validate.

Thank you.
