### ISSUE TITLE
How to import emitter in vue3 with ts

### ISSUE THREAD

**Issue by FrancescoMussi** [developit/mitt#130]
I am using vue3 with typescript.
This is how I currently init emitter using [globalproperties](https://v3.vuejs.org/api/application-config.html#globalproperties).

```js
import mitt from 'mitt';
const emitter = mitt();

const app = createApp(App);
app.config.globalProperties.emitter = emitter;
```

And this is how I use it in a component:

```js
mounted() {
  this.emitter.on('myEvent', this.onMyEvent )
},
```

It works. But I am getting this error in vs code:

`Property 'emitter' does not exist on type 'CreateComponentPublicInstance<{}, {}, ...`

Do you know how can I fix this?
Thanks!

**Comment by FrancescoMussi** [comment]
Okay maybe I found a way to fix it.

I have added this in shims-vue.d.ts:

```
import mitt from 'mitt';

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    emitter: mitt;
  }
}
```

The warning is gone. But this code was a bit improvised. Can you confirmed that it is the proper solution?

Thanks

**Comment by developit** [comment]
I have no idea tbh, that seems like a Vue-specific TypeScript question.

**Comment by tobias-feil-by** [comment]
It's true this is not an issue with mitt itself. However, if anyone like myself is coming here from a Google search, in Vue 3 it's best to use provide/inject for this instead of global properties as outlined [here](https://stackoverflow.com/a/66538941/7069126).

**Comment by Zahyron** [comment]
I tried Tobias solution, but had no success with it. When I inject the emitter I can't use it because the type is unknown. So I tried FrancescoMussi solution with _shims-vue.d.ts_ file. But when I add the code to _shims-vue.d.ts_ I get the following error for all my components:

> Could not find a declaration file for module 'x.vue'

My shims-vue.d.ts looks like this:
```
/* eslint-disable */
declare module '*.vue' {
  import type { DefineComponent } from 'vue'
  const component: DefineComponent<{}, {}, any>
  export default component
}

import mitt from 'mitt';
declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
      emitter: mitt;
  }
}
```

main.ts:
```
import { createApp } from "vue";
import App from "./App.vue";
...
import mitt from 'mitt';

const emitter = mitt();
const app = createApp(App)

app.component("FontAwesomeIcon", FontAwesomeIcon)
.use(router)
.use(store, key)
.provide('emitter', emitter)
.mount("#app");
```

Emitter usage:
```
import {defineComponent, inject} from 'vue';

export default defineComponent({
  name: 'App',
  setup (){
    const emitter = inject('emitter')
    return {
      emitter
    }
    
  },
    data() {
        return {
          ...
        };
    },
    methods: {
        test(){
          this.emitter.emit('hide-sidebar')
        }
      }
    });
```
Can someone help me please?

**Comment by Wasserwecken** [comment]
This might not the best solution, but I distribute the emitter with pinia. (im using pinia anyway):

Pinia store:
```typescript
import mitt from 'mitt'
import { Emitter, EventType } from 'mitt'
import { defineStore } from 'pinia'

export const useEventStore = defineStore('event', {
    state: (): Emitter<Record<EventType, unknown>> => mitt(),
});
```

Listener:
```typescript
import { useEventStore } from './common/eventStore';
const eventStore = useEventStore();
eventStore.on('foo', e => console.log('foo', e));
```

Trigger:
```typescript
import { useEventStore } from './common/eventStore';
const eventStore = useEventStore();
eventStore.emit('foo', { a: 'b' })
```

**Comment by acantepie** [comment]
You should just use a signleton : 

EventBus.js : 
```
import mitt from "mitt";

export default mitt()
```

Then, on your component or on your pinia store : 
```
import EventBus from "../lib/EventBus";
...

EventBus.emit(...)
EventBus.on(...)
...
```

**Comment by ap1969** [comment]
> You should use a signleton :
> 

This was the solution for me. Thanks @acantepie
