### ISSUE TITLE
eslint error Emitter not found in 'mitt'  import/named

### ISSUE THREAD

**Issue by barnholdy** [developit/mitt#132]
`import mitt, { Emitter } from 'mitt'`

gives me eslint `error  Emitter not found in 'mitt'  import/named` (https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/named.md)

Where it should work (see: https://github.com/developit/mitt/blob/master/src/index.ts#L15).

Any ideas what is going wrong?

```
// .eslintrc.js

module.exports = {
  root: true,
  env: {
    browser: true,
    node: true,
  },
  extends: [
    '@nuxtjs/eslint-config-typescript',
    'prettier',
    'plugin:prettier/recommended',
    'plugin:nuxt/recommended',
  ],
  plugins: ['prettier'],
  rules: {},
}

```

**Comment by developit** [comment]
This is the expected behavior of `eslint-plugin-import`, see this PR:
https://github.com/benmosher/eslint-plugin-import/pull/1726

The recommendation from the maintainers of `eslint-plugin-import` is to use `type` imports, or disable `import/named` globally:

```js
import mitt from 'mitt'
import type { Emitter } from 'mitt'  // this is a type-only import and will be ignored by `import/named`
```
