### ISSUE TITLE
No overload matches this call.

### ISSUE THREAD

**Issue by XiaoLizi29** [developit/mitt#134]
No overload matches this call.
  Overload 1 of 2, '(type: "*", handler: WildcardHandler): void', gave the following error.
    Argument of type '"form-item-created"' is not assignable to parameter of type '"*"'.
  Overload 2 of 2, '(type: EventType, handler: Handler<itemValidate>): void', gave the following error.
    Argument of type '(fun: itemValidate) => void' is not assignable to parameter of type 'Handler<itemValidate>'.
      Types of parameters 'fun' and 'event' are incompatible.
        Type 'itemValidate | undefined' is not assignable to type 'itemValidate'.
          Type 'undefined' is not assignable to type 'itemValidate'.

**Comment by developit** [comment]
This is addressed by #114.
