### ISSUE TITLE
No overload matches this call.

### ISSUE THREAD

**Issue by ChenJuo** [developit/mitt#135]
Overload 1 of 2, '(type: "*", handler: WildcardHandler): void', gave the following error.    
 Argument of type '"form-item-created"' is not assignable to parameter of type '"*"'.   
Overload 2 of 2, '(type: string | symbol, handler: Handler<ValidateFunc>): void', gave the following error.     
Argument of type '(func: ValidateFunc) => void' is not assignable to parameter of type 'Handler<ValidateFunc>'.       
Types of parameters 'func' and 'event' are incompatible.         
Type 'ValidateFunc | undefined' is not assignable to type 'ValidateFunc'.           
Type 'undefined' is not assignable to type 'ValidateFunc'.

**Comment by developit** [comment]
This is addressed by #114.
