### ISSUE TITLE
Proposal for an alternative API

### ISSUE THREAD

**Issue by hornta** [developit/mitt#140]
I'm looking for a small typescript-friendly event emitter and I just found this library with a new major a day ago but I feel like the API could be a bit different to promote even better typescript support and tighter coupling between firing and listening to events. I'm just going to throw out an alternative and see how it sticks and if it can give some inspiration then great. 

I'm a heavy redux-toolkit user and by the look of the proposal you can spot many similiarities. One could say it's like redux-toolkit minus redux.

This design allows me to group all of my events in one place. I don't know if it's good or not but I like it because it gives me an overview of all of my apps events and I'm not longer worrying about typos. By the looks of the current API I found it challening to provide multiple type-safe events in the same emitter. Now I'm no typescript-ninja so I can't say it's easy setting this API to correctly infer the event types in the .on() method but I know it can be done because redux-toolkit did it https://github.com/reduxjs/redux-toolkit/blob/master/src/createAction.ts

```ts

const myEmitter = mitt();

/**
 * Setting up the event creators
 */

// event types are just for debugging/tracking purposes
const nextLevel = myEmitter.createEvent("next_level");
const entityKilled = myEmitter.createEvent("entity_killed");
const gameWon = myEmitter.createEvent("game_won");
const gameLost = myEmitter.createEvent("game_lost");
const pickupDrop = myEmitter.createEvent("pickup_drop");

// with prepare callbacks
const messageSent = myEmitter.createEvent("message_sent", (text: string) => {
	return {
		id: nanoid(),
		text,
		createdAt: new Date().toISOString(),
	};
});

/**
 * Creating events
 */
const nextLevelEvent = nextLevel(2);
// { type: 'next_level', payload: 2 }

/**
 * Firing/Emitting events
 */
emitter.emit(nextLevel(2));


/**
 * Acting on events
 */
emitter.on(messageSent, (event) => {
	// messageSent.text
	// messageSent.id
	// messageSent.createdAt
});
```

**Comment by developit** [comment]
This is a really interesting proposal, but it's out of scope for Mitt. Mitt is just an event bus, not a state management library.
