### ISSUE TITLE
TS Error: "Unsafe assignment of an `any` value" when trying Readme example.

### ISSUE THREAD

**Issue by Lietsaki** [developit/mitt#141]
See [screenshot.](https://prnt.sc/172pr9m)

I'm trying to implement the example from the README.md in the following way using mitt 3.0.0 and with `"strict": true` in tsconfig.json
```
import mitt, { Emitter } from 'mitt';

type Events = {
  foo: string;
  bar?: number;
};

const emitter: Emitter<Events> = mitt<Events>();

export default emitter;
```

But the emitter const gets the **"Unsafe assignment of an `any` value"** error.

Am I missing something here?

**Comment by Lietsaki** [comment]
Error solved itself on window reload.

**Comment by khus29** [comment]
@Lietsaki , 

How do you manage to use emit API on emitter? Is number type accepted as a message?
`emiiter.emit('foo', 10)`

It is giving an error - Is not assignable to parameter of type 'string'
