### ISSUE TITLE
[TypeScript] TypeScript generic type

### ISSUE THREAD

**Issue by JaylanChen** [developit/mitt#142]
```
type TFsBaseToolEvent = {
  startTool?: string;
  cancelTool?: string;
};


interface IbaseTool<T extends TFsBaseToolEvent = TFsBaseToolEvent> {
  test: (s: T) =>void;
  event: Emitter<T>;
  event2: Emitter<TFsBaseToolEvent>;
}

class BaseTool<T extends TFsBaseToolEvent = TFsBaseToolEvent> implements IbaseTool<T> {
  event: Emitter<T>;
  referenceEvent: Emitter<TFsBaseToolEvent>;
  constructor() {
    this.event = mitt();
    this.referenceEvent = mitt<TFsBaseToolEvent>();
  }

  test (param: T) {
    console.log(param.startTool);
    this.event.emit('startTool'); // There is no inference type prompt.

    this.referenceEvent.emit('startTool');
  }
}

```

[demo](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCiA3YA7GAVZVAXjgGcYoBLbAczgB8zEBbAIwgBsBuAKB4Hp+cAILY4wLLjgALAIbYAJh2BQ4AY3kJZAa1SaIYGJQjZZHcZPiyoNAK7McMAUPkKy0iLY5vsEeFGAYWygxWTgMM1tgHlBIWARCOAAJV2UoAB48OBJbbG1fAHdsAD5suAAKCUcALjg8AEps0owISgVeWOh4JBQ4AHVKbw0oBRTFNMyygCVgNWgFdPIqWgAaOFz8iCLi0pJyngBIHuBa3UQIADM6lcOq3Fq8AG0zy7qAXR5GombW9r5BEShKBQWSIOCvMzmNTBAK4DhggI0SjkFTANx3eBycYqUhwC7QOBhY4xcBdBK9TCOMZKFQAGWRMEmOTyhRKZWEwNB6WpEzwOw6pPix36gwUAGFrApKbgeXSGUy4DM5iNFhRqDQ1htWTt2ZzEOkBkNJbKMnzirxnCI4MxZGBwVcMeTgLjXAhpMBKKplQFSJBFOqLI4ZKkcQA6ElxbqJaUwE0AWVt6RjuNAMBwClxSvmScsBBQmpZWxKuzgCbA6UOLyuyYYcAA5AAqOs3A4xk308g5xykZ7Ac7VyykN6lRiG8WStshqAdxnJ4o8c18TrxahpqAXWRqVBoZiUGBrru4FMgNOKTOzbMxvPAAubbalADeh0htUn2KgZcPMFIi8OJnSADSfbiCe6a4lW6CDsU5THLUQGIGsWI0lAtQml+PbwcO9S1C0bS8AcJgwYQtSNs2wbvrUY7DKMU7ocU2HhL8FoERcFyAcBqZgXAEFzkRKBwX2iFTgA-KhtHJo8mH0ThTF-qxfEnPWTZCRRIpGiMaFzgxuF-Lcu6MvBIGnhm3F9q8vGwXA8FrBir6DpJfZvNpskHMA+nsWCnFnqZ-aQd20GWbkCjABc1BokZXESZhcDCVZwG1NgVRQM5eE8AAvv8DYNjwcANqWe4wA81BguUAB+ABMAAMlWsI0Fy5GoRgmGYgZSG5BUqHAQhgLYrCkL14a5XAAACpgONaBU5Xlw0BEEIS4g+cYFRluX8BGZLBRuXjwPV2CNcYYj6bOg4Rd5WYqlehC3tq0HPhwHCiX5MpTp+c6fK+R0qHRcBPkciQAOI4ColBqG+yHZIcByMJp9k8YOw6Q6OorUTD-n4ZCZQY-QjCJQUpa2uU9TMbNwRiE+kP8FlkNDcI+N2q8jpjc6CAQHAiIMqibhIWkeINU12CkOGBwHKtkOQjcFNU8LQ0zEiKKqJojrc51+KqDA7pwEikhOkLIvTWA1iyMwP1LOq9CkCw7AcGlTp1IkDOWCzcAcBzYiq2sBIAAakZ7eIEhjGKkNT+uG8bD4AGJ8wdNvK6okd7fzTsaPdcDUGzzp+qQqAwKzWs4K1TjS9NDhsCoADyVxHcHa3C-+hleSZcP+QpAkIeRyG1IDiVUKDlgmo0v3C3MAuYlOpC1ByIL6l3wO91SU4jusighWFbgkJCACEoY0IEClE5DByUFc5Sx6QA8Hwcp+hj1pDSCfU778LBwZU-wAcFnP0X5voZZzAClrI8WObxCS4jBmkGc6Fey+WTFhfCwsX7PwlsLSm2Ui6KjchALAhIxBKynH7NWGs85iGOLrIaABJK4ntY6+2ROCT6Cg1gY1PvaN0qAiG22sKgAIzBMFolISHEEYdTa0HNpbTgNthTXhYY6HOS92byzgFQqcvsLhQAgMwD2qhvZNk9sHEaBtBE-XjvtEwNtAFTmASaXmCcDpO24bwvRw0S6sHLpXSaRca4sTYvXUC3km5HgCsROKbdY6PRnj3MBKhz5P2HuQduaRx4iD1OkcJINIlQEXkFFeiU16EnulvHef9jiP2FkfCop9olPzKffd8lSn5X19C7LcNTkKC2oMFEAFcWlpEaDsUolU1gAEYSnwIvm-D+g8n7f1-v-OAjwnJwNGU-BBaUkEHBQXosh2AWi6DyeYZhqtWGa0oNrEhmyrhgB9I4NY2i6y+2YZw1O2yIC6DcLIC4a4nQAFobQwDUO6LmY9+F6IAHJ+EUgmbAthIRglCssOgpF4k4lTriXw8B+pgEjHw4OjiDFGxNmqERFs2DiNtngDWMjEiyOoDs6IaDhp4rDqIRAZiJAwGAcy8IkRUDlAgKwAAVrMeAtCAhzGYA4ZebzFBwEgAUFQ9UOD1DWAbUgWc3CyOAJuaQSKoCOOca4ia+5q6Q3agZDivjG5mQHM3Sy1kLAwEelFRydTlCj3fLide+Tt672KYs6pFTP5PwON05FshQF9ynBAiS-jvxYQvgcH+TTgCE3jaGG0YByghuSk0QNQbL5TkqBgGAG8RnwJGRlA+zDPUcAKbvUiIz-VjzqcGh5uIxwShGOkqNUF6iptIEmlNea00EyzV8R88b83vlmWyktiyy2LJWYcNKvAK0Aiyuujdm6t3bp3buvd+6D2HqPcek9O6+DCgAEJhuAHgCAnAYxlCfHAMgMBrD4DvQ9WowiaC8GfRoPab9b2cEet+ldFoeCrnlZuVAZDWDXqAxwSYDdcRXqzghh9JBUM3o-TGcdz60zkFqOURJDQmg6V-QXD6HVTSLmfRicqVH9xfSw+hywi4K1qA4GGlD8GP1IYtTxtDOHHaYd4-etjqdmBgGUBK78cBYNicQ3yT+dHLCMYPHyCjAQLiogAzGdTzHFO4Yo7EigthGrQEJip59bpkShkdCQI6hMKP4ekHZ7TumtwYcNYyFjwnHDQX3s+it+HnTwHKIyh458bPqBMKQTgwBQwcAgDQCLocf6vtgAhoLNn1Z2YxPZ-S5Q6zkDfQhusRMupCHJaiFFcBfBPJ07CLcttLnqMMINGzOVctucFh55rwAYyFb3MV0rWWP0VYoxlNKQA)

Line: 145

**Comment by developit** [comment]
I have no idea what is causing this.

**Comment by reskes** [comment]
I tried fiddling around a bit with the code, but unfortunately came to no viable solution. But also would suggest that the issue has maybe to do with the way the emit-function in mitt is implemented.
Added some lines of code and comments as I was testing. Maybe it has some use for anyone who wants to make an attempt: [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBCYMYBo4G84FEBuBTAOxgBUBPMPNLRZPKOAXzgDMoIQ4AiGmTgbgBQAgPTC4AKklTpM2XPkLFS5StVr1coTHJ44AcUJ1gAY1yEYAZzgBeOACU8x6ABMAPGaJkKaAK4EA1gQQAO4EAHyCAtoUcMQAYhYAQgCGFnjEEBAANh7wtugCcHAWMMmwGdkA-ABcxTBQwAQA5nxwonDGABbJzXjOcDCdwFas7HAQYDDAEATJWQMQcHgAHmBZJkhwPf0WycFbBHDOwMzMdOZLp47wM+M+9DwAtI0lPcZ4FoUdb3hZFVk1OoNZqCBiRASNGB0ZjJd5wACSACNUulMllXMQlssoQRnFZ4kkUf9cjZYgkUmlifgiGEMF8oSVagAKCy1YgAShsYRwEGAzkERTw1JgtWoSChUFcBgIRlMwosES+QvMxFFPDoGMVRSgeDOOoI71yavFGoJFNR2VyioYQmMWVSVnN-wxWJxeLJhMpaJJtjNRO9wtpoDWeBA5isSP92U1dMFwuNtEl0tluQVAqWwtV2HVkuIWrgOr1hEN8ezJtz5KjOUD6acBBKUB8xhg0CZnIKRSKg2GADplURSTwpYYGnLw2E2+minWSgMPiQ2aT0GC2mI0roQKQOuwwwPnCFDojfiEvtOZhZsnge1kIE0mQySOypwMhhY+5nB+LNZPTy-e4XzgNPAfQQL8-S9S1Ax-IobXpec4CZMAymSEA2XbX8Z0va9b0Q5CQB7V5yjRJ9f27N9+xgPsaCZAByQiSDRGinzgUjX3fFUqKQWj6P+JjWnaTpzlY-9dUAktzE4mBuNKIjsj4r4bVg4RxDgOJoDgdYZTgAAmAA2OBNl2UhWQEFSaOXGiDKsB1gCaWZESyXQWxfXQZ3qZJIXGZgBh0OAaOIGi0ERHx4H8yynB8LJ+iPAz61KIhgGSKF+mCJBOi2I4TiLAcLB8RFol0CBvLcqAPIHfzKwg6tzBo0zhCEZTTOwKA2HoAABTTdAAZgAVmqJqAEEoCaHxdxubyCr8zgeLRThLOGOAgngGy7OSBynMWJDSrDCUvJ8mIaL8ZxdUaPpXUId1iAAbWmmSGOyTgAF04EqLgZoeuBahlfAoBons6ttc94GRNIW2yABVXETplZwvF0WwZX2J00UnVc-ysYIIEi-o5gvOAYsgCwLGAda0DxzFGjgZHsjgTHsfx3QjuhvpXoAeXoAArHxZ1eLcdRAMrxkOSbwItaqiEqIQQbwMGskh47mFO2GdB7B8mQ7JYWugWp6h8SgBAYZj2jANgeX8RomgOTXWoWOAmhlhBoF0F5bM6SwtkRLH4GCbp4G6MAKHrOBBJ1QG4vxlFZeTUc4dJRGqarYcZVHVMJxIgRpajkcTDh1X53VpUtagHXG31w3+LXPBneWrI8dhd5JisMi0AWsjg5CAyYDohA8B6eBnJi7mWbD2dM7ROO8CRxPRapcw08iMfsjzkoC6Kd6slqGiH0Cg2nyAA)

**Comment by iyegoroff** [comment]
You can write `this.event.emit('startTool', undefined);`

**Comment by JaylanChen** [comment]
> You can write `this.event.emit('startTool', undefined);`

Yes, you could write code like this;  But the problem is, when you write code, there's no event type inference, it's not friendly.

**Comment by sgoodgrove** [comment]
I assume this is because the compiler can't know the type of `<T>` in `event: Emitter<T>;` and therefore can't know what keys would be valid events for `this.event.emit('startTool');` because `<T>` may contain `'pauseTool'` or any other key... or it may not.

If you want the mitt instance to respond to events from `TFsBaseToolEvent` then it needs to be defined with that type (`event: Emitter<TFsBaseToolEvent>;`)

**Comment by barelyhuman** [comment]
Here's the explanation, it's not specifically a bug but more like a misconception of how the inferring works 

https://github.com/microsoft/TypeScript/issues/48741#issuecomment-1101637791

**Comment by JaylanChen** [comment]
> Here's the explanation, it's not specifically a bug but more like a misconception of how the inferring works
> 
> [microsoft/TypeScript#48741 (comment)](https://github.com/microsoft/TypeScript/issues/48741#issuecomment-1101637791)

Thank you, it was helpful.
