### ISSUE TITLE
warn Package mitt has been ignored because it contains invalid configuration. 

### ISSUE THREAD

**Issue by cyzaoj** [developit/mitt#143]
warn Package mitt has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/aoj/xxxxxx/node_modules/mitt/package.json
                                                      
                        #######                       
                   ################                   
                #########     #########               
            #########             ##########          
        #########        ######        #########      
       ##########################################     
      #####      #####################       #####    
      #####          ##############          #####    
      #####    ###       ######       ###    #####    
      #####    #######            #######    #####    
      #####    ###########    ###########    #####    
      #####    ##########################    #####    
      #####    ##########################    #####    
      #####      ######################     ######    
       ######        #############        #######     
         #########        ####       #########        
              #########          #########            
                  ######### #########                 
                       #########

**Comment by developit** [comment]
Nothing imports Mitt's package.json. I'm not sure what generated this warning for you, but it could probably be updated to avoid assuming package.json files are intended to be importable resources.
