### ISSUE TITLE
Using Symbol for event type breaks TypeScript support

### ISSUE THREAD

**Issue by ilicmarko** [developit/mitt#144]
Is there a reason `EventType` is also a `Symbol`?

https://github.com/developit/mitt/blob/13905bd4009e83f1876f2d31419e23cdbf4f9b48/src/index.ts#L1

This will create a problem if you want to type mitt, because of this issue https://github.com/microsoft/TypeScript/issues/1863.

This is because `EventType` is used to extend the generic type on `Emitter` and the key is `EventType`.

https://github.com/developit/mitt/blob/13905bd4009e83f1876f2d31419e23cdbf4f9b48/src/index.ts#L21

This is not support in TypeScript < 4.4, which is not even released. Because if you try it now it will fail

```
Type 'EventType' is not assignable to type 'string | number'.
        Type 'symbol' is not assignable to type 'string | number'.
```

Example event:
```ts
export interface CustomEvents {
	[name: string]: unknown;
	save: void;
}
```

**Comment by ilicmarko** [comment]
It looks I made a mistake but not explicitly defining the return type. Ignore.

**Comment by lil5** [comment]
I'm having this issue as well

The code below returns an error

```ts
import mitt, { EventType } from "mitt"

// Error:
// An interface can only extend an object type or intersection of 
// object types with statically known members.ts(2312)
interface Events extends EventType {
	"progress.set": (n: number) => void
	"progress.reset": () => void
}

// Error:
// Type 'Events' does not satisfy the constraint 'Record<EventType, unknown>'.
// Index signature for type 'string' is missing in type 'Events'.ts(2344)
const emitter = mitt<Events>()

export default emitter
```
