### ISSUE TITLE
[Feature request] Register multiple event listeners

### ISSUE THREAD

**Issue by martinszeltins** [developit/mitt#147]
Right now the `on()` function accepts only string as an argument but it would be very useful if we could listen for multiple events and use the same handler function.

For example instead of doing this:

```js
emitter.on('user-registered', () => {
    sendEmail()
})

emitter.on('special-day', () => {
    sendEmail()
})
```

... this could be easier done like this

```js
emitter.on(['user-registered', 'special-day'], () => {
    sendEmail()
})
```

**Comment by mrichar1** [comment]
This is (indirectly) covered in #127 - the solution is probably to capture all events using the wildcard option, then do your own matching' - something like:

```
emitter.on('*', (type) => {
  if (['user-registered', 'special-day'].includes(type)) {
    sendEmail()
  }
}
```

**Comment by developit** [comment]
The tradeoff here isn't worthwhile for Mitt, since there are other reasonable ways to achieve this. In addition to @mrichar1's suggestion, you can also do this:

```js
const onEmailTrigger = () => {
    sendEmail()
};
emitter.on('user-registered', onEmailTrigger);
emitter.on('special-day', onEmailTrigger);
```

Or, if you want, just add your own `onMultiple` function:

```js
function onMultiple(emitter, events, handler) {
  for (let event of events) emitter.on(event, handler);
}
```
