### ISSUE TITLE
[units test] how to test emitter.on()

### ISSUE THREAD

**Issue by Zeus-Iqd** [developit/mitt#149]

**Comment by cogor** [comment]
# Example with Jest:
I have emitter service(emitter.js)
```javascript
import mitt from "mitt";
const emitter = mitt();
export default emitter;
```
Example test
```javascript
import emitter from "./path-to-your-file/emitter.js";
jest.mock("./path-to-your-file/emitter.js");

describe("Some test name", () => {
  it("Right event after click", async () => {
    // some test code
    expect(emitter.emit).toHaveBeenCalledWith("right_event_name");
  })
});

```

**Comment by tsiotska** [comment]
Apparently you connect mitt in your main.js like that:
`app.config.globalProperties.emitter = emitter;`

So to make it work with tests as real event bus you can connect it to your jest.setup file as mocks:
`import { config } from '@vue/test-utils';
import mitt from 'mitt';

const emitter = mitt();
config.global.mocks = {emitter}
`

**Comment by udoedo** [comment]
@tsiotska kudos to you, thx
