### ISSUE TITLE
mitt.off('*') doesn't work

### ISSUE THREAD

**Issue by feliperaul** [developit/mitt#150]
The docs state that the `.off` method accepts a star string to remove all event handlers:

```
type (string | symbol) Type of event to unregister handler from, or '*'
```

However, in my test, this does not work, and I can't understand how it could, since the source code is very simple and Map.get('*') will not return all handlers.

Is this a never-implemented feature and the docs are wrong?

**Comment by feliperaul** [comment]
Just to be extra clear, aren't we missing something like this in the .off method?

```js
if (!type || type === '*') all.clear(); return 
```

**Comment by developit** [comment]
The docs are unclear here:  `.off('*')` doesn't remove all listeners, it removes all _wildcard_ (`*`) listeners:

```js
const events = mitt();

// add two wildcard listeners:
events.on('*', (type, e) => console.log(type, e));
let count = 0;
function countEvents(type) { count++; }
events.on('*', countEvents);

// Remove a specific wildcard listener:
events.on('*', countEvents);

// remove all wildcard listeners:
events.off('*');
```
