### ISSUE TITLE
Cypress support for mitt

### ISSUE THREAD

**Issue by gitSwaroop** [developit/mitt#151]
Hi Team,

I have used mitt for my project and I have used micro frontend
I am emitting event from one micro frontend  app to other which is working fine.  
I am writing test cases by using cypress library I am not able to mock event in cypress integration test.
https://docs.cypress.io/guides/overview/why-cypress

**Comment by developit** [comment]
To mock events, you'll need to expose mitt on `window`:

```diff
const events = mitt();   // somewhere in your code
events.on('my-event', (arg) => console.log(arg));

+window.events = events;
```

From Cypress you should be able to invoke your events like you can in app code:

```js
cy.window().its('events').invoke('emit', 'my-event', 'some-arg');
```
