### ISSUE TITLE
Typescript errors when defining event types?

### ISSUE THREAD

**Issue by djneely** [developit/mitt#152]
We've setup a global emitter to be used across components. When trying to define the event type we're seeing type errors. I believe we've followed the Typescript usage guide but something still appears off. Is this an issue or what is being defined wrong?

```
type Event = {
  data: string;
};
const eventBus: Emitter<Event> = mitt<Event>();
```

But then the editor is showing the attached errors.

![Screen Shot 2021-10-27 at 1 36 37 PM](https://user-images.githubusercontent.com/981157/139118107-d42e090c-6278-41b9-8b35-7cf693d365d9.png)
![Screen Shot 2021-10-27 at 1 36 51 PM](https://user-images.githubusercontent.com/981157/139118108-ec855ac4-bc18-4a0f-b7b2-7ba1c79d65a9.png)

**Comment by sokolinivan** [comment]
Did you manage to solve this problem somehow?

**Comment by developit** [comment]
Are you using [mitt 3.0.0](https://github.com/developit/mitt/releases/tag/3.0.0)? This feature was only added in that version.

**Comment by developit** [comment]
I can't reproduce this - it [works in the TS playground with Mitt 3.0.0](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBCYMYBo4G84FFHIKZRwC+cAZlBCHAEQB0A9AHYQAmeA+iKwK4A2eAZ3q4Y1ANwAoCTACeYPNgBueRvAC8GCXDgsAhjF0AuOAJhRgjAOaSikgMYRGpuHmWqAQtwHGcSGAQAeLDcYAD44DREgkNCACgBKSQlXFRhPAVo8XFiAcj0DHLQc0ggIHMSpeno4GAALQQUBWog+FjgAIwVZeRcoCihvZJD0zOy8-V1CuAAWACYKlI8vUaRciDqCcskgA0. It's likely a version or IDE configuration issue.

**Comment by khus29** [comment]
@developit ,

Why emit API second parameter is always string expected?

`import mitt, { Emitter } from "mitt";

type Event = {
  data: string;
  bar: string | number
};
const eventBus: Emitter<Event> = mitt<Event>();

eventBus.emit('data', 'foo');

eventBus.emit('data', 42); //this should not give error

// these should be type errors:
eventBus.emit('other');`

**Comment by avxkim** [comment]
@developit it works with type:

```js
type Events = {
  openregister: boolean
}

const emitter: Emitter<Events> = mitt<Events>()
```

but with `interface Events {}` it throws an error, that TS mentioned. Is that bug?

**Comment by erhsilence** [comment]
> @developit it works with type:
> 
> ```js
> type Events = {
>   openregister: boolean
> }
> 
> const emitter: Emitter<Events> = mitt<Events>()
> ```
> 
> but with `interface Events {}` it throws an error, that TS mentioned. Is that bug?

I encountered the same problem. It appears that the interface does not have an implicit index signature, and that's why you can't pass the interface. If you would add the index signature, the error will disappear:
``` typescript
interface Events {
  openregister: boolean
  [key: string | symbol ]: unknown
}

const emitter = mitt<Events>()
```
