### ISSUE TITLE
Use mitt in TypeScript, Override error （ts(2769)）, but it can still work

### ISSUE THREAD

**Issue by CodingGorit** [developit/mitt#155]
**Context**
I create a project with vite + vue3.2 + ts. and my tsconfig.json  use `"strict": true,`

**Target**
I am writing form components, I use mitt to listen formItem' s validation.

I define a callback function like this
```js
        type ValidateFunc = () => boolean;
        // ....
        const callback = (func: ValidateFunc): void => {
            console.log("add item =>", func);
        }
```

the result
```js
import mitt, { Emitter } from 'mitt';

export const emitter: Emitter<Events> = mitt<Events>();
type Events = {
    formItemCreated: (func: ValidateFunc) => void,
}

emitter.on('formItemCreated', callback);  // ts(2769)

emitter.off('formItemCreated', callback); // ts(2769)
```

but my project can run normally, and I set "strict" false in my tsconfig.json, the ts error disapper

Is this normal?

**Comment by LeonardoRain** [comment]
I have the same problem.

**Comment by CodingGorit** [comment]
> hhhh，this course's version is 2.2.1, but we use the latest version
