### ISSUE TITLE
[question]support  function rest array?

### ISSUE THREAD

**Issue by yurizhang** [developit/mitt#156]
// I want to transmits multiple parameters in emit:

emitter.on('foo', (...restArray))=>{
    console.log(restArray)   // forward to print:  ["a","b","c"]
    // I fonud restArray onle have a element.
}

// multiple parameters
emitter.emit('foo', "a","b","c")

I'm from vue2 user, now update to vue3 meet a question.
window.APP.$eventBus.$emit("toggleParentCEvent","data", data);

**Comment by developit** [comment]
Only a single `event` parameter is supported. This is done for size and performance reasons.
