### ISSUE TITLE
cannot cancel subscription

### ISSUE THREAD

**Issue by wyhPro** [developit/mitt#159]
`mitt.on('a',()=>{})`
When I write as above, why cannot cancel subscription

**Comment by developit** [comment]
You need to have a reference to the event handler in order to unregister it:

```js
const a = () => {};
mitt.on('a', a);

// cancel:
mitt.off('a', a);
```

**Comment by khus29** [comment]
@developit , If we have multiple subscriptions, like

`const a = () => {};
mitt.on('a', a);
mitt.on('a', a);
mitt.on('a', a);`

how do we cancel a specific one?

`mitt.all` gives us all the events but how to find which one to cancel?

**Comment by developit** [comment]
Those are all equal subscriptions. Mitt will always remove the first match, like Node's EventEmitter.
