### ISSUE TITLE
Typescript issue with `moduleResolution: NodeNext`

### ISSUE THREAD

**Issue by Mister-Hope** [developit/mitt#166]
Typescript cannot find types for mitt when targeting esm while declaring `moduleResolution: NodeNext`.

```ts
import mitt from 'mitt';
// or 
import { default as mitt } from 'mitt';
```

Getting

```
error TS7016: Could not find a declaration file for module 'mitt'. '/home/mister-hope/projects/vuepress-theme-hope/node_modules/.pnpm/mitt@3.0.0/node_modules/mitt/dist/mitt.mjs' implicitly has an 'any' type.
```

The problem is that the export field is missing declaration file, also the project is not outputing a `index.d.mts` for `index.mjs`.

**Comment by developit** [comment]
Fixed in #167.
