### ISSUE TITLE
`dist/mitt.mjs` must not have a sourcemap

### ISSUE THREAD

**Issue by mvorisek** [developit/mitt#168]
![image](https://user-images.githubusercontent.com/2228672/194652689-46d9a556-caf2-41c4-a10f-46c2410145cd.png)

this is a problem for non-minified webpack builds as the source comments are not removed leading to browser console warning on every page:

![image](https://user-images.githubusercontent.com/2228672/194652809-5099b4ad-2df5-4cec-886c-5ba06b0454dd.png)

affected version: 2.10 and 3.0.0

this should be fixed asap for 2.x and 3.x

**Comment by mvorisek** [comment]
reproducible on https://dev.agiletoolkit.org/demos/index.php

needed for webpack with non-minified output (such webpack output is more or less concatenation of source files which must no contain sourceMappingURL comment)

**Comment by mvorisek** [comment]
We bundle many libs and this is the only problematic one - why the npm dep source/dist should be minified? It cannot be debug when webpacked. The dist files should be not minified, then sourcemap would also not be needed.

**Comment by rschristian** [comment]
> why the npm dep source/dist should be minified?

It's opinionated, but the authors of a lib are able to minify the source further than consumers can (safely) do. This results in slight improvements in bundled.

> It cannot be debug when webpacked

That's what the source maps are for.

**Comment by mvorisek** [comment]
thank you for your reply

I solved the problem by installing https://webpack.js.org/loaders/source-map-loader/ webpack loader.
