### ISSUE TITLE
Interactive blog post about mitt

### ISSUE THREAD

**Issue by viebel** [developit/mitt#17]
Hi 
Extremely cool lib!

It would be great if you write an interactive blog post about mitt. Showing it in action in the browser. 

It is super simple to do it with the [klipse plugin](https://github.com/viebel/klipse). 

Take a look for instance at my posts about [es2017](http://blog.klipse.tech/javascript/2016/12/21/es2017-await.html) or [setTimeout](http://blog.klipse.tech/javascript/2016/10/31/setTimeout-0msec.html).

**Comment by developit** [comment]
Hi there!  I'm open to PRs to add any examples and the format doesn't matter to me, but I don't intend to blog about this library. Typically the readme examples in repos I maintain are just Codepens or JSFiddles.  I'll definitely look into Klipse for my blog though, cheers!

**Comment by viebel** [comment]
Cool!
What is the address of your blog?

**Comment by developit** [comment]
It's over at [jasonformat.com](https://jasonformat.com).

**Comment by viebel** [comment]
Very nice blog! 

I've been also blogging [about jsx](http://blog.klipse.tech/javascript/2016/12/14/jsx.html) but I found the klipse embedding much more natural than the codepen one. Also the snippets share the same scope: sometimes it is convenient when you want to build a story in your blog post.
