### ISSUE TITLE
Unpkg CDN Version is down

### ISSUE THREAD

**Issue by nvasileiadis** [developit/mitt#170]
The https://unpkg.com/mitt@1.1.3/dist/ is down. 
This broke our software using your package via a CDN.
The error code is 520 in Cloudflare.

**Comment by rschristian** [comment]
If I'm understanding correctly, Unpkg had an outage? If so, there's nothing for `mitt`, nor any package, to do or fix.

Part of the risk of relying on a CDN is that service could go down at any time without warning. If that risk is too great, you can always self-host your dependencies.
