### ISSUE TITLE
Can't pass multiple arguments with emit

### ISSUE THREAD

**Issue by soorajsprakash** [developit/mitt#187]
Hi,
I tried to pass multiple arguments from the emit, and only the first one is getting passed, others when called is returning as undefined.

Example:

* When a click happens, I'm sending this event:
`emitter.emit("download-clicked", fieldName, fieldValue)`

* And in another place, i check for this function:
`emitter.on("download-clicked", this.onDownloadClick)`

where `onDownloadClick` is the function to get triggered when that event is detected.

* Function is as below:
```
onDownloadClick(name: string, value: string) {
    console.log("name: ", name)
    console.log("value: ", value)
    // other steps of the function
}
```

* Here the name is showing correctly, while the variable "value" is showing as `undefined`

**So, can I really pass multiple variables as arguments from within the emit?**

***

EDIT: 
* If i club the multiple arguments into an object, its working as expected. So what's the catch here. Is this supposed to work like that ? Or, is this a bug?
` emitter.emit("download-clicked", { name: fieldName, value: fieldValue } )`  => This works

**Comment by LiahMartens** [comment]
AFAIK mitt only supports a single argument

**Comment by developit** [comment]
This is by design, variable arguments are both a performance footgun and poor design - when you change the arguments you now have to change all listeners, which defeats much of the purpose of using events in the first place. An object with properties is preferable and already supported.
