### ISSUE TITLE
Star handlers called without the event type as the first arg

### ISSUE THREAD

**Issue by oaleynik** [developit/mitt#2]
Looks like all star handlers should be called with `type` as first argument, aren't they?

![image](https://cloud.githubusercontent.com/assets/609229/21965688/b255461c-db6d-11e6-8f72-611aa85f0fad.png)

**Comment by developit** [comment]
heh! I only realized after publishing that I'd made the wrong call there but then tweeted the right one. Thanks for the PR.

**Comment by tunnckoCore** [comment]
just sorry for the offtopic... @oaleynik which is that theme that you are using?

**Comment by developit** [comment]
@tunnckoCore that's actually my editor - I commented with the setup [in this issue](https://github.com/developit/asyncro/issues/2#issuecomment-270369137) (apparently people really like my editor setup haha).

**Comment by tunnckoCore** [comment]
Haha, great. I'll try the syntax theme. Few weeks on Atom and can't find meaningful theme, tried dozen but all are absolutely awful.

**Comment by oaleynik** [comment]
@tunnckoCore yeah, that screenshot is the ctrl+c/ctrl+v from Twitter :)
Currently I use https://github.com/apex/apex-ui and https://github.com/apex/apex-syntax from @tj - I found it super "disruption free" because of absence of the color noise.

Some other themes I like include:
- Chester
- Github Atom Light
- Material
- Gloom
- One Dark Vivid

It of course depends on the mood, time of the day when I work, moon phase, etc.. :)

@developit very sry for the offtopic :)

**Comment by developit** [comment]
One Dark Vivid for life (though now I'm looking at Gloom)

**Comment by tunnckoCore** [comment]
@oaleynik holy shit, so clean and enough, I'll try it, because screenshot is not enough for me :) Thanks again.

So TJ is still so amazing person, haha.

> very sorry for the offtopic :)

meh.. it happens some times :laughing:

**Comment by tunnckoCore** [comment]
Btw, a bit on topic.

What about that (fixes this issue, resolves #12, 197b and in bonus: you can access the `all`)

```js
let ret = {
  all: {},
  on (type, handler) {
    list(type).push(handler)
    return ret
  },
  off (type, handler) {
    let e = list(type)
    e.splice(e.indexOf(handler) >>> 0, 1)
    return ret
  },
  emit (type, event) {
    list(type).map((f) => f(event))
    list('*').map((f) => f(type, event))
    return ret
  }
}

let list = (type) => ret.all[type = type.toLowerCase()] || (ret.all[type] = [])

module.exports = () => ret
```

**Comment by tunnckoCore** [comment]
Damn, I'm god? 179b with #8 

```js
let mitt = {
  all: {},
  on (type, handler) {
    list(type).add(handler)
    return mitt
  },
  off (type, handler) {
    list(type).delete(handler)
    return mitt
  },
  emit (type, event) {
    list(type).forEach( f => f(event))
    list('*').forEach( f => f(type, event))
    return mitt
  }
}

let list = (type) => mitt.all[type = type.toLowerCase()] || (mitt.all[type] = new Set())

export default () => mitt
```

usage

```js
var mitt = require('./dist/mitt')
var ee = mitt()

ee.on('*', (type, arg) => console.log('wildcard:', type, arg)) // => wildcard: foo 123
ee.on('foo', (arg) => console.log('foo:', arg)) // => foo: 123
ee.emit('foo', 123)
```

**Comment by tunnckoCore** [comment]
So in short. Can I PR with fixing #2, #3, #12, #13 and bonus accessing `all`?

**Comment by developit** [comment]
@tunnckoCore your implementation returns the same instance for every `mitt()` call, which means listeners are shared for all instances. It needs to return a new instance for each `mitt()` call so it's not just a singleton.

**Comment by tunnckoCore** [comment]
Hm. Actually, yea. I get some tests.
