### ISSUE TITLE
Use semantic release tooling?

### ISSUE THREAD

**Issue by sospedra** [developit/mitt#20]
Now that changes are coming it's gonna be crucial that we don't break past implementation without warning users. I propose using something like this: https://github.com/semantic-release/semantic-release

I'm open to help with the integration.

**Comment by developit** [comment]
I'm up for a PR for sure, I've been looking to switch to that module or @sindresorhus' [np](https://github.com/sindresorhus/np).  It would be really useful to compare the two.

**Comment by tunnckoCore** [comment]
I'm using `standard-version` which fits to my flow very better. I kinda like to have more control an do these two things manually and separately. I always release v1 using git-release (from git-extras TJ's package) when have tests and totally green services, then just use standard-version for the next versions, then if everything is green just npm publish.
