### ISSUE TITLE
1k stars - hoooraaayy

### ISSUE THREAD

**Issue by tunnckoCore** [developit/mitt#22]
Haha. :tada: 

@EmilTholin is the 1000th!

![2017-01-18-23 45 02_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/22084215/de25f75c-ddd7-11e6-9cdb-444b2cbaf102.png)

**Comment by EmilTholin** [comment]
I just had to make a gif out of it when I saw the star count!

![mitt](https://cloud.githubusercontent.com/assets/11573167/22084582/faf95cd6-ddd0-11e6-8849-d2cce6f937c9.gif)

**Comment by developit** [comment]
you guys are hilarious 🤣

**Comment by tunnckoCore** [comment]
Haha, we could close that. :)
