### ISSUE TITLE
expose `all`

### ISSUE THREAD

**Issue by Lokua** [developit/mitt#27]
I think...

`off(type)` should remove all handlers for the given type

`off()` without arguments should just clear the `all` object completely 

# OR...

you can just expose `all`! it'll only be an addition of 4 chars, and I won't bother you anymore (or at least that's my story) ;P

**Comment by developit** [comment]
Likely can't do either of the first features in such a small lib. 

`all` is already exposed:

```js
let all = {};
let e = mitt(all)
delete all.foo
```

**Comment by svincent** [comment]
@developit that's true today, but #19 changes that to use a private internal `let all = Object.create(null)`.

**Comment by developit** [comment]
Indeed. I'm fine exposing all, just whichever way is smaller.  Could always combine:

```js
function mitt(all) {
  all = all || Object.create(null);
}
```

**Comment by Lokua** [comment]
Oh man I'm an idiot. Glad I brought it up though considering. Thanks 😀

**Comment by tunnckoCore** [comment]
@developit i was able to do it, but intentionally change that variant because the size limit. We could add it again but it cost 5bytes haha. :)

**Comment by tunnckoCore** [comment]
#19 also solves this. Even final size is 196b from few days :D

**Comment by developit** [comment]
@tunnckoCore I can't remember - did we check the filesize difference between accepting `all` as an argument VS exposing it as a property?
