### ISSUE TITLE
TransformError in react-native

### ISSUE THREAD

**Issue by IljaDaderko** [developit/mitt#31]
I believe some babel presets within mitt's package.json are causing following error when used in react-native

NOTE: adding those preset into project itself fixes the issue, but I'm not entirely sure if this it is a good solution to force presets? And it would be good to find out where and how mitt needs these to weight everything.

Loving the project so far <3 I converted my personal project to use mitt alongside slightly altered version of smitty (https://github.com/tkh44/smitty) and it seems much cleaner / easier compared to redux so far, great job 👍 

Error received in react native v0.40, mitt 1.0.0
---
![Imgur](http://i.imgur.com/aElMpky.png)

**Comment by IljaDaderko** [comment]
Looks like #24 references this same issue. Will babel config be moved out into separate .rc file by any chance? It might take a while for facebook to make their and adding these babel presets to host project seems like a stab to the app :/

**Comment by developit** [comment]
Yup, I'm happy to merge that PR as a short term solution.

**Comment by IljaDaderko** [comment]
@developit awesome, will get rid of the presets and wait for new package release 👍 thank you.

**Comment by developit** [comment]
@IljaDaderko Released as [1.0.1](https://github.com/developit/mitt/releases/tag/1.0.1)!
