### ISSUE TITLE
Clean up repo root

### ISSUE THREAD

**Issue by developit** [developit/mitt#38]
- [x] Auto-generate (and gitignore) `typings.json` during build via [package-to-typings](https://www.npmjs.com/package/package-to-typings)
- [x] move `mitt.d.ts` into `src/` (it's still included in the npm package)
- [x] Move `.babelrc` into `tests/` since that's the only place it's used
- [x] gitignore `yarn.lock`
- [x] remove `example.js` (started in #37 - should be in the readme instead)

/cc @tunnckoCore

**Comment by tunnckoCore** [comment]
1. How? :rofl: Is there any need to add something to the package.json?

**Comment by developit** [comment]
Yeah it's in the readme for that package. Basically just an npm script to invoke the module and a typings field.

**Comment by lazarljubenovic** [comment]
`yarn.lock` [shouldn't be ignored](https://github.com/yarnpkg/yarn/issues/1583) though.

**Comment by developit** [comment]
Just commented about this on another repo - I think the issue with not ignoring `yarn.lock` is that it then _requires_ a maintainer to use Yarn.  If they don't the lockfile becomes out of sync with the package.json.

**Comment by vutran** [comment]
> Just commented about this on another repo - I think the issue with not ignoring yarn.lock is that it then requires a maintainer to use Yarn. If they don't the lockfile becomes out of sync with the package.json.

Perhaps `husky` precommit hook to run `yarn` would help here.
