### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by tunnckoCore** [developit/mitt#40]
Isn't just enough to not use babel and etc? Why we need this and ES6 syntax and imports at all. It is just overhead. With that we can just remove babel from deps and they will look more clean.

/cc @developit

**Comment by developit** [comment]
@tunnckoCore maybe we can just drop Babel and switch from `babel-register` to `buble/register`?  The tests aren't async (and likely don't ever need to be), so bublé should be enough for them

**Comment by tunnckoCore** [comment]
Don't know if `buble` has register, but don't see to they to be ES6 et al ;d needless more dev time, but that's self preference.

**Comment by tunnckoCore** [comment]
@developit, actually no, we can just use `buble/register`, because Buble itself does not understand import/exports. https://github.com/rollup/rollup/issues/657#issuecomment-220786674

If we change them to use  require()s, we totally can just use plain node. We don't have strong need to be ES6.

**Comment by tunnckoCore** [comment]
Meh.. currently I don't see any easy switch - followed few threads but not seems better than current approach with babel and tons of devDeps. As I'm building @Rolldown and [Muka v1](https://github.com/tunnckoCore/mukla/issues/12) i can come with a solution for better testing and config around that ecosystem and not using Babel, AVA or such.

**Comment by developit** [comment]
Buble and switching to requires seems decent enough.

**Comment by tunnckoCore** [comment]
if we switch to requires not make sense to use buble et al since we run tests only on node 6

**Comment by developit** [comment]
true, node 6 has arrow functions right? that's all I cared about

**Comment by tunnckoCore** [comment]
Yea, exactly. So we can just switch to `require`s and remove the whole test build overhead, just using mocha and arrows.

**Comment by developit** [comment]
I'm not against that, if you're up for it.  Nice to drop the babel dep given it was only for testing.

**Comment by tunnckoCore** [comment]
cool, i'll do that in a free time.

> or you know, we write a 500b test framework

haha, yea. actually pretty easy idea btw, for around mid 2017 or early 2018 when everything is ES6 (or at least node v4). also i'm working on minimal framework too ;p

**Comment by developit** [comment]
wondering if rollup (or something) could be used to speed things up.

**Comment by tunnckoCore** [comment]
yeap, the cli of that small fw would run through rollup ;p thats on my todo and is in process :))

**Comment by tunnckoCore** [comment]
actually mentioned rolldown project, so presets and plus import/export support included. kinda how ava works under the hood

**Comment by nmakod** [comment]
@developit , @tunnckoCore , I think this issue is no longer relevant and can be closed ?
