### ISSUE TITLE
[feature request] once handler

### ISSUE THREAD

**Issue by Andarist** [developit/mitt#54]
would u consider adding this or is it out of scope? Ive tried implementing it myself so I could send a PR, but my minifications skill are not that great ;)

best result i got was `214B` which is exceeding ur goal

**Comment by tunnckoCore** [comment]
A lot of things and implementations were declined because that strict limit, so probably no.

You might be interested in https://github.com/tunnckocore/dush, which is around ~300-400b, with all needed things, and can have micro plugins.

**Comment by rangermeier** [comment]
As reference for anyone looking for this functionality: It's possible to add a `once` method:

```js
const emitter = mitt()
emitter.once = (type, handler) => {
    const wrappedHandler = (evt) => {
        handler(evt)
        emitter.off(type, wrappedHandler)
    }
    emitter.on(type, wrappedHandler)
}
```

**Comment by plehnen** [comment]
@rangermeier this will not work when you try to unregister the handler via .off() before it was called at least "once".
(e.g. if you open a dialogue and register the once handler, close it and unregister with off, and re-open and again register with once. Once the event is emitted, the handler will now be called twice!)
