### ISSUE TITLE
I want to remove all handlers at once

### ISSUE THREAD

**Issue by ZhouHansen** [developit/mitt#57]
How about `emitter.off()` then remove all handlers , and `emitter.off('noLonger')` then remove all handlers belong to it？

**Comment by svincent** [comment]
I'm going to crib @tunnckocore's answer on #54 and suggest that you take a look at [dush](https://github.com/tunnckocore/dush). Mitt has a very strict 200 byte limit, so adding features is a real challenge. Dush already has the behavior you described and is only slightly larger.

**Comment by ZhouHansen** [comment]
thx

**Comment by developit** [comment]
```
let all = {}
let events = mitt(all)

events.reset = () => {
  for (let i in all) delete all[i]
}
```

**Comment by tunnckoCore** [comment]
Yep. It is simple reset [here](https://github.com/tunnckoCore/dush/blob/master/src/index.js#L229).

**Comment by developit** [comment]
ah, I only read the issue title.

**Comment by ZhouHansen** [comment]
thx, makes me to keep using mitt.

**Comment by mehdi-cit** [comment]
I went for a slightly different version. Disposing of reset and adding a line to the overridden off:
```
events.off = (type, handler) => {
  if(!type) {all ={}; return;}  
  if (!handler) delete all[type]
  else return off(type, handler)
}
```

**Comment by charlike** [comment]
@ZhouHansen @mehdi-cit, in any way you add bytes, so it not make any sense to me to do that instead of just using `dush`, which is exactly because of this is 100-200 bytes bigger than `mitt`.

Closing, since solutions are found.
