### ISSUE TITLE
Uncaught TypeError: mitt is not a constructor

### ISSUE THREAD

**Issue by JonWallsten** [developit/mitt#60]
Hi!
Im trying to use mitt in our react project using typescript.
But I get this error in runtime: 

```
Uncaught TypeError: mitt is not a constructor
    at eval (api.ts:11)
    at Object../packages/foo-api/api.ts (bundle.js:10804)
    at __webpack_require__ (bundle.js:672)
    at fn (foo.js:98)
    at eval (index.ts:5)
    at Object../packages/foo-api/index.ts (bundle.js:10817)
    at __webpack_require__ (bundle.js:672)
    at fn (bundle.js:98)
    at eval (Foo.view.tsx:15)
    at Object../packages/foo-ui/Foo.view.tsx (bundle.js:11779)

```

I'm using ut just like in your example
```
import * as mitt from 'mitt'
const emitter: mitt.Emitter = new mitt()
```

When debugging in Dev tools and check mitt it's an object, not a contructor.
```
Object {__esModule: true, default: function}
   default: function mitt(all )
   __esModule: true
   __proto__: Object
```

Am I doing something wrong?

**Comment by RapidTransit** [comment]
```
const path = require('path');

    resolve: {
        extensions: ['.ts', '.js', '.tsx', '.less'],
        modules: ['./src', 'node_modules'],
        alias: {
            "mitt": path.resolve(__dirname, './node_modules/mitt/dist/mitt.umd.js')
        }
    },
```
Webpack loads the ES6 Source (because I think mitt points to it by default), you will need to override the main  in mitt's `package.json` by tweaking the file location in your webpack config.

**Comment by developit** [comment]
Hi there - don't import * as mitt, just import it directly:

```js
import mitt from 'mitt';
```

**Comment by RapidTransit** [comment]
That works with just Webpack but it won't work with just Typescript.

**Comment by JonWallsten** [comment]
@developit "[ts] Module '"mitt"' has no default export."
@RapidTransit I'll try that. Thanks!

**Comment by FromTheCodeCave** [comment]
We are converting a component that uses mitt from JavaScript to TypeScript. I installed the last version, 1.1.3, but still encountering "mitt is not a constructor". Followed the TypeScript approach mentioned. 

Any recommendations on resolving would be appreciated?

**Comment by DavidHooper** [comment]
Here is how you can work around the issue for now without messing with Webpack.

```
import * as Mitt from 'mitt/dist/mitt.umd';
import { Emitter } from 'mitt';

const emitter = new Mitt() as Emitter;
```

**Comment by developit** [comment]
For folks encountering this: you need to set `compilerOptions.allowSyntheticDefaultImports` to `true` in your tsconfig.json. Doing that will make TypeScript resolve the module's default export the same as Webpack does, so you don't get errors in either:

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
  }
}
```
