### ISSUE TITLE
Thanks !

### ISSUE THREAD

**Issue by RakanNimer** [developit/mitt#61]
I use a lot of code that you develop and open-source.
I never run into issues that cant be solved by re-reading the docs (and/or in rare cases the code) so I never open issues in here and am using this as a chance to.
I suspect there are many people like me :)

Thanks to @developit ( and all contributors ! ) for the great work !
Cheers 😄

**Comment by charlike** [comment]
Yea, he's a **PRO**, just like me :rofl:
