### ISSUE TITLE
[question] off(*) behaviour

### ISSUE THREAD

**Issue by Andarist** [developit/mitt#70]
shouldnt it remove all listeners instead of only listeners attached with `on('*', fn)`? alternatively it would be good to have some `destroy` method to remove all listeners, whatsoever, that could be even achieved with `emitter.off()` (when called without arguments)

**Comment by developit** [comment]
No - wildcards are an event type of their own, they simply match all fired events. If the behavior was changed, it'd make it impossible to unregister a `*` listener. Your other suggestion was discussed here, and there are a few different solutions provided that don't require extra code in mitt:
https://github.com/developit/mitt/issues/27
