### ISSUE TITLE
Question: do you want to make `once()` available?

### ISSUE THREAD

**Issue by rafaelrinaldi** [developit/mitt#74]
One of the things I find useful about event emitters/signals is the ability to emit an event/signal only once.

I understand this library aims to have a super small footprint, but I do believe adding such feature would not add significant size to the final bundle.

With that being said, do you have interest in adding this feature? If so, I can attempt a PR.

Thank you.

**Comment by olstenlarck** [comment]
https://github.com/developit/mitt/issues/57
https://github.com/developit/mitt/issues/54
