### ISSUE TITLE
Unable to use extend with mitt

### ISSUE THREAD

**Issue by TheAifam5** [developit/mitt#78]
Hey,
I noticed that after when I try to use extends in my TypeScript project, the all class stuff are just removed. 

Also I need to use ugly hack to execute the constructor of mitt beacuse `TypeError: mitt is not a constructor`.
```
const mittConstructor = (mitt as any).default.prototype.constructor;
type ExampleClassEmitter = StrictEventEmitter<mitt.Emitter, IExampleEvents>;
class ExampleClass extends (mittConstructor as { new(): ExampleClassEmitter }) {}
```

So I need to do like this to get inheritance:
```
const mittConstuctor = (mitt as any).default.prototype.constructor;
class MittFix {
  constructor() {
    Object.entries(mittConstuctor()).forEach(([key, value]) => {
      this[key] = value;
    });
  }
}

class ExampleClass extends (MittFix as { new(): ExampleClassEmitter }) {}
```

That's because Mitt constructor returns an object { ... }, and 'this' is not used, but should be.

Regards,
TheAifam5

**Comment by olstenlarck** [comment]
What about this one?

```js
class MittFix {
  constructor() {
    const emitter = mitt()

    Object.keys(emitter).forEach((method) => {
      this[method] = emitter[method]
    })
  }
}
```

Strongly believe it would work.

**Comment by TheAifam5** [comment]
So I using TypeScript and with code like this:
```js
import * as mitt from 'mitt';
class MittFix {
  constructor() {
    const emitter = mitt();

    Object.keys(emitter).forEach((method) => {
      this[method] = emitter[method];
    });
  }
}
```
Does not work because `Value of type 'MittStatic' is not callable. Did you mean to include 'new'?`.
With `new` also does not help.
Importing like `import mitt from 'mitt';` says `[ts] Module '"mitt"' has no default export.`.

**Comment by developit** [comment]
Hi there - `mitt()` is not a constructor, it's a function. I believe our TS types lie about that right now.

**Comment by developit** [comment]
This may be fixed with the latest 1.2.0 release, let me know if anyone is still experiencing the issue.

**Comment by ashbrener** [comment]
We are also experiencing this issue

**Comment by bwgjoseph** [comment]
I am not able to extend `Mitt` as well.

**Comment by developit** [comment]
Mitt is not a class, and as such it cannot be extended.

If you need to create a class version of mitt, I believe the following TypeScript code should suffice:

```ts
import mitt from 'mitt';
export class Mitt {
  constructor(e) {
    Object.assign(this, mitt(e));
  }
}
export interface Mitt extends mitt {}
```

**Comment by deskoh** [comment]
Submitted #97 to address the above, else the workaround is as follows:

```ts
declare module 'mitt' {
  interface Emitter {
    on(type: 'foo', handler: (e: { bar: string }) => void): void;
    
    // Won't improve type checking due to existing catch-all typings
    off(type: 'foo', handler: (e: { bar: string }) => void): void;
    // Won't improve type checking due to existing catch-all typings
    emit(type: 'foo', e: { bar: string }): void;
  }
}
```

**Comment by Nishchit14** [comment]
I can't able to work with the instances of a `mitt`, I have two tabs __(nth tab)__ and each tab would only listen to its private mitt instance. but now if I emit from tab-2, tab-1 is also listening its event, which should be avoided in my case. any help?

**Comment by developit** [comment]
Closing since the types have been completely rewritten since this was opened. Mitt is still not a class and thus cannot be extended as if it were a class, but that's not going to change.
