### ISSUE TITLE
Publish latest changes please

### ISSUE THREAD

**Issue by joeljeske** [developit/mitt#81]
It appears that there are some valuable changes in master. Are there bugs or issues preventing a release? I would love to see them published as a new version. 

Thanks!

**Comment by developit** [comment]
Sorry about that!

**Comment by levrik** [comment]
@developit I was trying to use `mitt` with TypeScript but had to find out that changes required to make it work aren't publish. Please publish a new version!

**Comment by vagusX** [comment]
how it going now?

**Comment by developit** [comment]
Just published `1.2.0` with the fixes! Sorry for taking an eternity on this, I'm going to spend a bit of time bringing Mitt's repo and build setup into 2020 this week.
