### ISSUE TITLE
TypeScript: Wildcard types did not make it into 1.1.3

### ISSUE THREAD

**Issue by atrauzzi** [developit/mitt#82]
Just looking at the source package of 1.1.3 and the release notes mention that the wildcard typing was added.

Unfortunately, it looks like 1.1.3 still has the old typing definition.  Any chance you can trigger a release of 1.1.4 with the updated wildcard typing?

**Comment by vagusX** [comment]
+1

**Comment by developit** [comment]
Will publish!

**Comment by atrauzzi** [comment]
Lovely!
