### ISSUE TITLE
Restrictions for the event name

### ISSUE THREAD

**Issue by agudulin** [developit/mitt#9]
This code will produce an exception:

```js
const mitt = require("mitt")

const emitter = mitt()

emitter.on('constructor', e => console.log(1))
emitter.emit('constructor', {})
```

You may want to filter all those native methods out, or use a different approach of collecting the events.

**Comment by developit** [comment]
Hmm - good call, this might be another reason to use `set`. Another interesting solution: prefix all types with `:` when storing them on the object.

**Comment by fix-fix** [comment]
@developit or you can use prototype-less objects with `Object.create`, which is supported in IE9.

Example for current code:
```diff
-all = all || {};
+all = all || Object.create(null);
```

More on this: http://www.2ality.com/2013/10/dict-pattern.html

**Comment by developit** [comment]
That's a great idea, I used to use it in Preact. I guess I'd be fine with saying IE9+ instead of "literally any JS runtime" 🤠
