### ISSUE TITLE
"*" listeners may fire more than once.

### ISSUE THREAD

**Issue by elijahdorman** [developit/mitt#93]
If you want to only target `"*"` listeners and do `emitter.emit("*", "stuff here")`, those listeners will actually fire twice. Checking for that specific value before firing the `"*"` listeners would fix that.

**Comment by developit** [comment]
Is this a use-case Mitt should support? The point of `*` listeners is that they are not individually addressable.

**Comment by vitkarpov** [comment]
@developit may I ask a question on this if you will? As you said before `*` listeners couldn't be directly addressable, so do you think it makes sense to warn people about this explicitly while trying to do this, like:

```js
// console.warn says something like "the actions are skipped since wildcard listeners are not individually addressable"
emitter.emit('*')
```

I think it'd be fewer questions like that, wouldn't it?

**Comment by developit** [comment]
Warnings aren't an option in a <200 byte library. TypeScript typings could warn against this, but otherwise it's a documentation issue IMO.

**Comment by vitkarpov** [comment]
Yeah, typings + a note in documentation seems reasonable (the next question could be answered by a link to it). Would you consider a PR on that or you think it's minor?

**Comment by developit** [comment]
Hiya @vitkarpov - sorry for not responding. I would definitely accept a PR to add docs/typings/warnings for this.

**Comment by developit** [comment]
Added to the typescript definition.
