### ISSUE TITLE
Improve perfomance

### ISSUE THREAD

**Issue by Kikobeats** [developit/mitt#98]
Hello,

I recently see a change at gatsby codebase where they modified the original mitt source code to use a slightly similar implementation but 25% faster:

https://github.com/gatsbyjs/gatsby/pull/23223/files#diff-57dc49b17585e7e09b4cabd11499e032R29

It could be interesting to implement these changes back to here!

Do would you accept a PR in that direction?

**Comment by developit** [comment]
Yeah, that seems like a compelling case. There are a few options here fwiw. Using Set is actually technically an API change, because it doesn't allow duplicate handlers, which EventEmitter allows.

**Comment by developit** [comment]
This should be fixed by #99 :)
